### ISSUE TITLE
Needs readme.txt and readme.md

### ISSUE THREAD

**Issue by benlk** [INN/gravity-forms-add-subtotal-merge-tag#1]
- [x] Needs to credit http://gravitywiz.com/subtotal-merge-tag-for-calculations/.
- [x] Needs to reference https://github.com/INN/gravity-forms-donate-boilerplate

**Comment by benlk** [comment]
- [ ] Needs to credit http://gravitywiz.com/subtotal-merge-tag-for-calculations/.

**Comment by aschweigert** [comment]
just a very simple readme.txt would be sufficient here
