### ISSUE TITLE
Will we be releasing this on wp.org?

### ISSUE THREAD

**Issue by benlk** [INN/gravity-forms-add-subtotal-merge-tag#2]

**Comment by benlk** [comment]
My gut feel on this one is 'no', because it's merely our fork of http://gravitywiz.com/subtotal-merge-tag-for-calculations/ .

**Comment by aschweigert** [comment]
nope, not our plugin so it's fine if we have a repo with a very basic readme but i don't want to spend time on docs/improvements/etc. to it necessarily unless we really need to
