### ISSUE TITLE
Subtotal Not Functioning

### ISSUE THREAD

**Issue by arudd20** [INN/gravity-forms-add-subtotal-merge-tag#3]
I'm using the latest versions of WordPress (5.0.3) and Gravity Forms (2.4.5). The Subtotal feature isn't functioning when I preview my form. It seems there hasn't been an update to this plugin in some time. Could you help me identify the issue? Thanks for your help.
![screen shot 2019-01-30 at 11 03 34 am](https://user-images.githubusercontent.com/2379065/51998881-23b4aa80-247f-11e9-8957-93510ba9c469.png)

**Comment by benlk** [comment]
If it doesn't function when you preview, does it function in the live form?

**Comment by arudd20** [comment]
No, it doesn't work in either setting.

**Comment by benlk** [comment]
Does it work if you disable all plugins other than this plugin and Gravity Forms?

**Comment by arudd20** [comment]
@benlk I've disabled all of my plugins except Gravity Forms and required add-ons, plus I activated the WP default theme and the issue remains the same. Still, there is no calculation happening in the subtotal field. Any thoughts? I noticed there was an update on original plugin at GravityWiz on December 1 & 10, 2018. https://gravitywiz.com/subtotal-merge-tag-for-calculations/

**Comment by benlk** [comment]
Ooo, thank you for bringing that to our attention! We'll update this tiny plugin to reflect those upstream changes.
